### ISSUE TITLE
Merge the (original) XML Web Services specification source

### ISSUE THREAD

**Issue by kwsutter** [eclipse-ee4j/jax-ws-api#103]
Just an FYI...  The original (oracle) XML Web Services specification source is now available via this CQ:  https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21464

Please import/modify/merge it when time allows, hopefully in time for Jakarta EE 9.  Thanks!

**Comment by kwsutter** [comment]
Part of the work specified by the overall Jakarta EE 9 Issue #95.

**Comment by lukasj** [comment]
fixed by #105
