### ISSUE TITLE
Jakarta-ize the JSR-109 Enterprise Web Service specification document

### ISSUE THREAD

**Issue by andymc12** [eclipse-ee4j/jax-ws-api#118]
This issue is for tracking the work associated with converting the JSR-109 Enterprise Web Service specification doc.  This should require changing references of "Java EE" to "Jakarta EE", "JAX-WS" to "Jakarta XML Web Services", "javax.xml.ws" to "jakarta.xml.ws", etc.  Where applicable, the spec should also change links from the Java EE / JSR sites to the current Jakarta sites.

The doc to update is located here:
https://github.com/eclipse-ee4j/jax-ws-api/tree/master/enterprise-ws-spec/src/main/asciidoc

**Comment by sawadood** [comment]
I will update Chapter 9 and appendices with a new pull request.

**Comment by lukasj** [comment]
this can be closed I believe
