### ISSUE TITLE
Compatibility certification request for EI of JXWS 3.0.0-M5

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/jax-ws-api#149]
- [x] Organization Name ("Organization") and, if applicable, URL:
  [Eclipse Foundation](https://www.eclipse.org/)
- [x] Product Name, Version and download URL (if applicable):
  [Eclipse Implementation of Jakarta XML Web Services 3.0.0-M5](https://eclipse-ee4j.github.io/metro-jax-ws/index.html)
- [x] Specification Name, Version and download URL:
   [Jakarta XML Web Services 3.0](https://jakarta.ee/specifications/xml-web-services/3.0/)
- [x] TCK Version, digital SHA-256 fingerprint and download URL:
  [Jakarta XML Web Services TCK 3.0.0](https://download.eclipse.org/jakartaee/xml-web-services/3.0/jakarta-xml-ws-tck-3.0.0.zip), SHA-256: 7562e880b86893adff0e846fc265ee5feaf9ffea5ba32a151153755a376ad628
- [x] Public URL of TCK Results Summary:
  [TCK results summary](https://eclipse-ee4j.github.io/metro-jax-ws/TCK-Results.html)
- [x] Any Additional Specification Certification Requirements:
  None
- [x] Java runtime used to run the implementation:
  Oracle JDK 1.8.0_202
- [x] Summary of the information for the certification environment, operating system, cloud, ...:
  Linux
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by dblevins** [comment]
@lukasj The JXWS 3.0.0-M5 release doesn't seem to be available from the download link.  Is it possible to get that added or supply a different link as the download URL?

**Comment by lukasj** [comment]
@dblevins fixed. Again, wait a minute or two and force-refresh....

**Comment by dblevins** [comment]
Perfect!  Thank you!  Also, aren't you in EU timezone?  Super late for you!

**Comment by lukasj** [comment]
yup, CET TZ. I was only waiting for someone to check this and (finally) start the ballot ;-)

**Comment by dblevins** [comment]
Happening now, so you can crack open a nice Czech beer and celebrate in about 5 minutes :)

**Comment by lukasj** [comment]
accepted
