### ISSUE TITLE
Promote Jakarta XML Web Services 3.0

### ISSUE THREAD

**Issue by dblevins** [eclipse-ee4j/jax-ws-api#154]
I didn't realize we had added this finishing step of attaching this checklist, so these are more than likely already done.

 - [x] promotes api staging release promotes the specification api jars to maven central. An example release job script can be found here https://wiki.eclipse.org/MavenReleaseScript.
 - [x] go through the merged jakarta.ee specification website page to verify all the links are valid.
 - [x] approve the compatibility request.
 - [x] The compatible implementation project/vendor MUST send an email to tck@eclipse.org for approval of the compatible implementation for trademark usage.
 - [x] merge any final release branch as appropriate for the branch management for the project.

**Comment by lukasj** [comment]
done
