### ISSUE TITLE
There is no content after introduction section in the generated enterprise-ws-spec-1.4.pdf

### ISSUE THREAD

**Issue by jimma** [eclipse-ee4j/jax-ws-api#157]
https://jakarta.ee/specifications/enterprise-ws/1.4/enterprise-ws-spec-1.4.pdf

**Comment by lukasj** [comment]
for full spec see https://jakarta.ee/specifications/enterprise-ws/2.0/enterprise-ws-spec-2.0.pdf Only empty "empty" template was required for Jakarta EE 8 (v.1.4 of the spec)
