### ISSUE TITLE
Compatibility certification request for Eclipse Metro 4.0.0-M3

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/jax-ws-api#187]
- [x] Organization Name ("Organization") and, if applicable, URL:
  [Eclipse Foundation](https://www.eclipse.org/)
- [x] Product Name, Version and download URL (if applicable):
  [Eclipse Metro 4.0.0-M3](https://github.com/eclipse-ee4j/metro-wsit/releases/tag/4.0.0-M3)
- [x] Specification Name, Version and download URL:
   [Jakarta XML Web Services 4.0](https://jakarta.ee/specifications/xml-web-services/4.0/)
- [x] TCK Version, digital SHA-256 fingerprint and download URL:
  [Jakarta XML Web Services TCK 4.0.0](https://download.eclipse.org/jakartaee/xml-web-services/4.0/jakarta-xml-ws-tck-4.0.0.zip), SHA-256: fceaf20e7da6cc898ce46941b5f324968cef53f621c2e36ca5dea1ba616ddcb7
- [x] Public URL of TCK Results Summary:
  [TCK results summary](https://eclipse-ee4j.github.io/metro-wsit/TCK-Results.html)
- [x] Any Additional Specification Certification Requirements:
  None
- [x] Java runtime used to run the implementation:
  Oracle JDK 11.0.2
- [x] Summary of the information for the certification environment, operating system, cloud, ...:
  Linux
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by edbratt** [comment]
Please add the test result summary to the [TCK Results Summary](https://eclipse-ee4j.github.io/metro-wsit/TCK-Results.html) page.

**Comment by lukasj** [comment]
added

**Comment by lukasj** [comment]
accepted by lazy consensus
