### ISSUE TITLE
Compatibility certification request for EI of JXWS 4.0.0-M3

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/jax-ws-api#188]
- [x] Organization Name ("Organization") and, if applicable, URL:
  [Eclipse Foundation](https://www.eclipse.org/)
- [x] Product Name, Version and download URL (if applicable):
  [Eclipse Implementation of Jakarta XML Web Services 4.0.0-M3](https://github.com/eclipse-ee4j/metro-jax-ws/releases/tag/4.0.0-M3)
- [x] Specification Name, Version and download URL:
   [Jakarta XML Web Services 4.0](https://jakarta.ee/specifications/xml-web-services/4.0/)
- [x] TCK Version, digital SHA-256 fingerprint and download URL:
  [Jakarta XML Web Services TCK 4.0.0](https://download.eclipse.org/jakartaee/xml-web-services/4.0/jakarta-xml-ws-tck-4.0.0.zip), SHA-256: fceaf20e7da6cc898ce46941b5f324968cef53f621c2e36ca5dea1ba616ddcb7
- [x] Public URL of TCK Results Summary:
  [TCK results summary](https://eclipse-ee4j.github.io/metro-jax-ws/TCK-Results.html)
- [x] Any Additional Specification Certification Requirements:
  None
- [x] Java runtime used to run the implementation:
  OpenJDK 11.0.2+9
- [x] Summary of the information for the certification environment, operating system, cloud, ...:
  Linux
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by edbratt** [comment]
For reference, the TCK is staged at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/promoted/eftl//jakarta-xml-ws-tck-4.0.0.zip

**Comment by edbratt** [comment]
Could you please clarify -- [The TCK summary page](https://eclipse-ee4j.github.io/metro-jax-ws/TCK-Results.html): there are no different TCK results under 4.0 m3 results from earlier releases. Even if they are the same as those of the previous run, I would prefer that you paste the summary immediately following the certification data (i.e. after the 4.0m3 results and before the 3.0.1 results.)

**Comment by lukasj** [comment]
They're there now; I forgot to add them to the page

**Comment by lukasj** [comment]
accepted by lazy consensus
