### ISSUE TITLE
Public Release

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jax-ws-api#54]
Last CTS runs indicate no failures in this component. It's time to make a public release. Before the release make sure that Eclipse Release Review is passed and all dependencies have been released.

**Comment by Tomas-Kraus** [comment]
Release job passed: https://jenkins.eclipse.org/jaxws/job/nexus-staging-close/54/console
Dependency tree:
- jakarta.xml.ws:jakarta.xml.ws-api:jar:2.3.2
  - jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.2:compile
    - jakarta.activation:jakarta.activation-api:jar:1.2.1:compile
  - jakarta.xml.soap:jakarta.xml.soap-api:jar:1.4.1:compile
  - jakarta.annotation:jakarta.annotation-api:jar:1.3.4:compile
  - jakarta.jws:jakarta.jws-api:jar:1.1.1:runtime
All dependency tree artifacts were released to maven central.
Created PR https://github.com/eclipse-ee4j/jax-ws-api/pull/55 to merge release info into Ee4J_8 branch.
