### ISSUE TITLE
No such thing yet as "java.jws" - but it is required in V2.3.2 jaxws-rt-2.3.2.jar

### ISSUE THREAD

**Issue by rlblanken** [eclipse-ee4j/jax-ws-api#56]
Title says most of it.

"No such thing yet as "java.jws" - but it is required in V2.3.2 jaxws-rt-2.3.2.jar"

Thus we cannot use V2.3.2 in Java 11 because of module not found

**Comment by lukasj** [comment]
If this were true, one would not be able to build jaxws-rt-2.3.2.jar, which is built on jdk11.
Make sure that 'jakarta.jws:jakarta.jws-api:1.1.1' is on your module path

**Comment by rlblanken** [comment]
Cool. I searched Web for "java.jws" before sending first e-mail and could not find this. Exactly what I needed to know. Is there some way to find Maven artifacts by Java Module Name  that I have not learned?
