### ISSUE TITLE
Update Scope Statement for Jakarta API for XML-based Web Services Project

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/jax-ws-api#57]
Update the scope statement for the project: https://projects.eclipse.org/projects/ee4j.jakartaee-platform/governance

See https://docs.google.com/spreadsheets/d/1FPLjo_DJDOQngVtdrYgaDk98d9NBG-0ODgdmOG3LOsI/edit?usp=sharing for examples.

**Comment by lukasj** [comment]
looking at the example:

> Jakarta API for XML-based Web Services provides a specification document, API and TCK for XML-Based Web Services, XML Messaging and Web Services Metadata.

Using `XML Messaging` can be confusing as that is supposed to describe JAXM (basically a bridge between JMS and XML-based Web Services, not something what would be included in project repositories). `SOAP with Attachments` better describes what is provided from saaj-api repository.

So maybe something like this:

`Jakarta API for XML-based Web Services provides a specification document, API and TCK for XML-Based Web Services, Web Services Metadata and SOAP with Attachments.`?

**Comment by m0mus** [comment]
+1 to @lukasj proposal

**Comment by asoldano** [comment]
+1 to the proposal above

**Comment by waynebeaton** [comment]
If we focus just on what the specification defines (and adopt the name from #58), we end up with this.

> Jakarta XML Web Services defines a means for implementing XML-Based Web Services, Web Services Metadata, and SOAP with Attachments.

Does that work?

**Comment by ivargrimstad** [comment]
> If we focus just on what the specification defines (and adopt the name from #58), we end up with this.
> 
> > Jakarta XML Web Services defines a means for implementing XML-Based Web Services, Web Services Metadata, and SOAP with Attachments.
> 
> Does that work?

Yes!

**Comment by waynebeaton** [comment]
I've pushed forward with this specification statement:

> Jakarta XML Web Services defines a means for implementing XML-Based Web Services, Web Services Metadata, and SOAP with Attachments.

I have taken specification committee approval of this scope statement and have turned the project into a specification project based on it.

But we need a little more information here. I completely missed that this specification project holds three different specifications. We'll need a scope statement for each of:

- Jakarta SOAP Attachments
- Jakarta Web Services Metadata
- Jakarta XML Web Services

**Comment by lukasj** [comment]
what about sth like:

Jakarta SOAP with Attachments:
> Jakarta SOAP with Attachments defines API enabling developers to produce and consume messages conforming to the SOAP 1.1, SOAP 1.2 and SOAP Attachments Feature.

Jakarta Web Services Metadata:
>  Jakarta Web Services Metadata defines the syntax and semantics of Java Web Service (JWS) metadata and default values. This specification does not define a Java environment in which Web Services are run.

Jakarta XML Web Services:
> Jakarta XML Web Services defines a means for implementing XML-Based Web Services based on Jakarta SOAP with Attachments and Jakarta Web Services Metadata.

**Comment by waynebeaton** [comment]
I think that two out of three are good.

This one needs work.

>  Jakarta Web Services Metadata defines the syntax and semantics of **Java** Web Service **(JWS)** metadata and default values. This specification does not define a Java environment in which Web Services are run.

JWS is on the list of acronyms that we're not to use. I'm not aware of anything that's separately known as "Java Web Services" (and changing it to "Jakarta Web Services" makes it circular).

Based on a cursory review of the specification document... can we say:

> Jakarta Web Services Metadata defines a means of generating Web Services metadata (WSDL) from an annotated Java source file, Java stub code from WSDL, or a mapping between an existing Java source file and WSDL.

Or something like that.

**Comment by lukasj** [comment]
Ah, my bad, missed that `Java Web Service (JWS)`..

what about:

> Jakarta Web Services Metadata defines programming model for Web Services in Java, use of metadata, non-normative processing model for metadata annotated web service source file, runtime requirements for a container and annotations used for WSDL, binding and configuration.

**Comment by bshannon** [comment]
Small improvements to the grammar:

> Jakarta Web Services Metadata defines a programming model for Web Services in Java, use of metadata, a non-normative processing model for metadata annotated web service source files, runtime requirements for a container, and annotations used for WSDL, binding, and configuration.

> Jakarta SOAP with Attachments defines an API enabling developers to produce and consume messages conforming to the SOAP 1.1, SOAP 1.2, and SOAP Attachments Feature.

**Comment by waynebeaton** [comment]
I'm going to take the following the Jakarta EE Specification Committee for ballot approval.

> Jakarta XML Web Services defines a means for implementing XML-Based Web Services based on Jakarta SOAP with Attachments and Jakarta Web Services Metadata.

> Jakarta Web Services Metadata defines a programming model for Web Services in Java, use of metadata, a non-normative processing model for metadata annotated web service source files, runtime requirements for a container, and annotations used for WSDL, binding, and configuration.

> Jakarta SOAP with Attachments defines an API enabling developers to produce and consume messages conforming to the SOAP 1.1, SOAP 1.2, and SOAP Attachments Feature.

**Comment by lukasj** [comment]
closing since this has been already done
