### ISSUE TITLE
Change project name to Jakarta XML Web Services

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/jax-ws-api#58]
Background information:
https://waynebeaton.wordpress.com/2019/04/04/renaming-java-ee-specifications-for-jakarta-ee/

Checklist:
- [ ]  GitHub
- [x]  README file
- [x]  CONTRIBUTING file
- [x]  Eclipse Project under https://projects.eclipse.org/projects/ee4j

**Comment by ivargrimstad** [comment]
**Jakarta XML Web Services** or maybe simply **Jakarta Web Services**?

**Comment by lukasj** [comment]
I prefer **Jakarta XML Web Services** since this is really tight to XML world. Using the name without XML could possibly confuse people with REST.
