### ISSUE TITLE
Please verify that spec api artifacts for 2.3.3 are available on maven central

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/jax-ws-api#89]
Is the Jenkins job that handled the 2.3.3 spec api release pushing to Maven central?  

[Maven repo only seems to have 2.3.2](https://mvnrepository.com/artifact/jakarta.xml.ws/jakarta.xml.ws-api)

CC @lukasj + @Tomas-Kraus

**Comment by lukasj** [comment]
there's no 2.3.3 right now. It must go through ballot first

**Comment by lukasj** [comment]
No, just PRs: https://github.com/jakartaee/specifications/pulls

**Comment by scottmarlow** [comment]
Thanks, so then [specifications/pull#50](https://github.com/jakartaee/specifications/pull/50) is the ballot link that needs approval?

**Comment by scottmarlow** [comment]
I don't see a recent ballot email for "Jakarta XML Web Services" or "JAX-WS-API" on [jakarta.ee-spec ml](https://www.eclipse.org/lists/jakarta.ee-spec/maillist.html), do we need to send one still for 2.3.3 so it can be approved?

**Comment by scottmarlow** [comment]
From operations.adoc link above, the initiating email sent to emo@eclipse.org is private so we still have 5 more days before EMO might initiate the ballot with jakarta.ee-spec@eclipse.org email.  Sound right?

**Comment by lukasj** [comment]
this is done
